export type MediaType = 'image' | 'music' | 'video';
export type RatingSummary = { averageRating: number | null; reviewCount: number };
export type Review = {
  id: string;
  stars: number;
  text: string;
  createdAt: string;
  source: 'completed-order';
};
export type Seller = RatingSummary & {
  id: string;
  handle: string;
  displayName: string;
  bio: string;
  avatarUrl: string;
  payoutAddress: string;
};
export type PaymentEvidence = {
  network: 'pay-sandbox';
  signature: string;
  mint: string;
  slot: number;
  buyerAddress: string;
  sellerAddress: string;
  amountUsdc: string;
  buyerBalanceBefore: string;
  buyerBalanceAfter: string;
  buyerDelta: string;
  sellerBalanceBefore: string;
  sellerBalanceAfter: string;
  sellerDelta: string;
  verifiedAt: string;
};
export type StyleListing = RatingSummary & {
  id: string;
  sellerId: string;
  seller: Seller;
  name: string;
  description: string;
  tags: string[];
  priceUsdc: number;
  etaSeconds: number;
  type: MediaType;
  durationSeconds?: number;
  sampleImages: string[];
  publicPromptSummary: string;
  inputRequirements: string;
  commercialUseAllowed: boolean;
  createdAt: string;
  palette: string;
  featured: boolean;
};
export type PrivateStyleListing = StyleListing & { hiddenWorkflowPrompt: string };
export type GenerationJob = {
  id: string;
  styleListingId: string;
  inputImageUrl: string | null;
  buyerBrief: string;
  brandName: string;
  budget: number;
  desiredTags: string[];
  status: 'queued' | 'generating' | 'delivered' | 'failed';
  selectedByAgent: boolean;
  requestSource?: 'web' | 'agent';
  decisionReason: string;
  paymentStatus: 'pending' | 'confirmed';
  paymentMode?: 'simulated' | 'pay-sandbox';
  payoutAddress?: string;
  paymentVerificationError?: string | null;
  paymentReceipt?: {
    protocol: 'mpp';
    network: 'pay-sandbox';
    transaction: string;
    payer: string | null;
    recipient: string;
    amountUsdc: number;
    confirmedAt: string;
    evidence?: PaymentEvidence;
  };
  paymentConfirmedAt: string | null;
  priceUsdc: number;
  outputImageUrl: string | null;
  outputAudioUrl?: string | null;
  generationMode: string | null;
  executionMode?: 'local' | 'worker';
  workerName?: string | null;
  workerClaimedAt?: string | null;
  error: string | null;
  createdAt: string;
  updatedAt: string;
};
export type JobWithStyle = GenerationJob & { style: StyleListing; review?: Review | null };
