'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import {
  ArrowLeft,
  ArrowRight,
  Check,
  CheckCircle2,
  Clock3,
  Download,
  LoaderCircle,
  Laptop,
  RotateCcw,
  Sparkles,
} from 'lucide-react';
import type { JobWithStyle } from '@/lib/types';
import { api } from '@/lib/client';
import { Avatar, StyleArtwork, Tags, Usdc } from './ui';
import { PaymentProof } from './payment-proof';
import { paymentReady } from '@/lib/payment-mode';
export function JobView({ initialJob }: { initialJob: JobWithStyle }) {
  const [job, setJob] = useState(initialJob);
  const [error, setError] = useState('');
  const [paying, setPaying] = useState(false);
  const [copied, setCopied] = useState(false);
  const sandbox = job.paymentMode === 'pay-sandbox';
  const advancing = useRef(false);
  const done = job.status === 'delivered';
  useEffect(() => {
    if (job.status === 'delivered' || job.status === 'failed') return;
    let stopped = false;
    async function tick() {
      try {
        const latest = await api<JobWithStyle>(`/api/jobs/${initialJob.id}`);
        if (stopped) return;
        setJob(latest);
        setError('');
        if (
          latest.executionMode !== 'worker' &&
          paymentReady(latest) &&
          !advancing.current &&
          !['delivered', 'failed'].includes(latest.status)
        ) {
          advancing.current = true;
          void api(`/api/jobs/${initialJob.id}/advance`, {})
            .catch((e) => {
              if (!stopped) setError(e.message);
            })
            .finally(() => {
              advancing.current = false;
            });
        }
      } catch (e) {
        if (!stopped) setError((e as Error).message);
      }
    }
    void tick();
    const interval = setInterval(tick, 1000);
    return () => {
      stopped = true;
      clearInterval(interval);
    };
  }, [initialJob.id, job.status, job.paymentStatus]);
  async function retry() {
    try {
      setError('');
      await api(`/api/jobs/${job.id}/retry`, {});
      setJob(await api(`/api/jobs/${job.id}`));
    } catch (e) {
      setError((e as Error).message);
    }
  }
  async function pay() {
    setPaying(true);
    try {
      setError('');
      if (!sandbox) await new Promise((resolve) => setTimeout(resolve, 1500));
      await api(`/api/jobs/${job.id}/pay`, {});
      setJob(await api(`/api/jobs/${job.id}`));
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setPaying(false);
    }
  }
  return (
    <div className="page-wrap job-page">
      <Link className="back-link" href="/jobs">
        <ArrowLeft size={15} />
        My creations
      </Link>
      <div className="job-heading">
        <div>
          <div className="eyebrow muted">CREATION / {job.id.slice(0, 8).toUpperCase()}</div>
          <h1>
            {done
              ? 'Now that’s an impression.'
              : job.status === 'failed'
                ? 'A small creative interruption.'
                : 'Good taste takes a moment.'}
          </h1>
          <p>
            {done
              ? 'Your brief. Your creator’s perspective. Something entirely yours.'
              : job.status === 'failed'
                ? 'Your order is saved. Retry without another payment.'
                : 'Your idea is finding its new point of view.'}
          </p>
        </div>
        <span className={`status-pill ${done ? 'delivered' : ''}`}>
          {done ? <CheckCircle2 size={14} /> : <Clock3 size={14} />}
          {done
            ? 'Delivered'
            : job.paymentStatus === 'pending'
              ? job.paymentReceipt
                ? 'Verifying payment'
                : 'Awaiting payment'
              : job.status === 'failed'
                ? 'Needs a retry'
                : 'In the studio'}
        </span>
      </div>
      {job.executionMode === 'worker' && (
        <div className="worker-handoff" aria-live="polite">
          <Laptop size={23} />
          <div>
            <strong>
              {done
                ? `Generated on ${job.workerName}`
                : job.status === 'generating'
                  ? `Generating on ${job.workerName}`
                  : job.status === 'failed'
                    ? 'Seller worker interrupted'
                    : `Waiting for @${job.style.seller.handle}’s laptop`}
            </strong>
            <p>
              {done
                ? job.generationMode === 'local'
                  ? 'Generated by a local AI model on the seller’s machine, then uploaded to the marketplace.'
                  : 'Composed on the seller’s machine in mock mode, then uploaded to the marketplace.'
                : 'This order runs on the seller’s worker. If it is paused or offline, the order waits; the marketplace does not generate it.'}
            </p>
          </div>
          <span className="demo-badge">SELLER WORKER</span>
        </div>
      )}
      <div className="job-grid">
        <section className="result-panel">
          {done && job.outputImageUrl ? (
            <>
              <div className="result-image">
                <img
                  src={job.outputImageUrl}
                  alt={`Generated ${job.style.name} image for ${job.brandName || 'your brief'}`}
                />
              </div>
              <div className="result-toolbar">
                <div>
                  <CheckCircle2 size={18} />
                  <span>
                    Your creation, ready to go.
                    <small>
                      {job.generationMode === 'mock'
                        ? 'Demo composition · 1024 × 1280 PNG'
                        : job.generationMode === 'local'
                          ? 'Local AI generation · PNG'
                          : 'AI-generated image · PNG'}
                    </small>
                  </span>
                </div>
                <a
                  className="button button-dark"
                  href={`${job.outputImageUrl}?download=1`}
                  download
                >
                  Download image <Download size={16} />
                </a>
              </div>
            </>
          ) : (
            <div className={`generation-stage ${job.status === 'failed' ? 'failed' : ''}`}>
              <div className="generation-orbit">
                <span>✳</span>
                <i />
                <i />
              </div>
              <span className="eyebrow">
                {job.status === 'failed'
                  ? 'LET’S GIVE THAT ANOTHER GO'
                  : 'YOUR IDEA, IN GOOD HANDS'}
              </span>
              <h2>
                {job.paymentStatus === 'pending'
                  ? 'One step from something good.'
                  : job.status === 'queued'
                    ? job.executionMode === 'worker'
                      ? 'Waiting for your seller’s studio.'
                      : 'Your spot in the studio is ready.'
                    : job.status === 'failed'
                      ? 'The studio hit a snag.'
                      : job.executionMode === 'worker'
                        ? 'Your seller’s laptop is at work.'
                        : 'A new perspective is taking shape.'}
              </h2>
              <p>
                {job.error ||
                  (job.paymentStatus === 'pending'
                    ? sandbox
                      ? job.paymentReceipt
                        ? 'Your settlement receipt is saved. Chain verification must pass before generation starts.'
                        : 'Pay with your local pay.sh agent or terminal. Test USDC settles on the Pay sandbox before your seller starts.'
                      : 'Confirm the simulated payment to start your creation.'
                    : 'Bringing your brief and your creator’s signature style together.')}
              </p>
              {job.status === 'failed' && (
                <button className="button button-dark" onClick={retry}>
                  <RotateCcw size={16} />
                  Retry generation
                </button>
              )}
              {!paymentReady(job) && sandbox && job.paymentReceipt && (
                <div>
                  <p>Settlement receipt saved. Generation waits for chain verification.</p>
                  {job.paymentVerificationError && (
                    <p className="error-message">{job.paymentVerificationError}</p>
                  )}
                  <button className="button button-dark" onClick={pay} disabled={paying}>
                    {paying ? 'Verifying transaction…' : 'Retry chain verification'}
                  </button>
                  <p className="mode-note">Rechecks the existing transaction. No second payment.</p>
                </div>
              )}
              {job.paymentStatus === 'pending' && sandbox && !job.paymentReceipt && (
                <div>
                  <button
                    className="button button-dark"
                    onClick={async () => {
                      const command = `pay --sandbox curl -X POST '${window.location.origin}/api/jobs/${job.id}/pay'`;
                      try {
                        await navigator.clipboard.writeText(command);
                        setCopied(true);
                      } catch {
                        window.prompt('Copy and run on your laptop:', command);
                      }
                    }}
                  >
                    {copied ? 'Payment command copied' : 'Copy pay.sh payment command'}
                  </button>
                  <p className="mode-note">
                    Run the command in your terminal. This page updates automatically after payment.
                  </p>
                </div>
              )}
              {job.paymentStatus === 'pending' && !sandbox && (
                <button className="button button-dark" onClick={pay} disabled={paying}>
                  {paying && <LoaderCircle className="spin" size={16} />}Pay{' '}
                  {job.priceUsdc.toFixed(2)} demo USDC
                </button>
              )}
              <span className="generation-caption">
                {job.paymentStatus === 'pending'
                  ? sandbox
                    ? 'PAY.SH SANDBOX · TEST USDC ONLY'
                    : 'SIMULATED PAYMENT · NO REAL FUNDS'
                  : `ESTIMATED STYLE DELIVERY: ~${job.style.etaSeconds}s`}
              </span>
            </div>
          )}
          <div className="job-progress" aria-live="polite">
            {['queued', 'generating', 'delivered'].map((s, i) => {
              const current = ['queued', 'generating', 'delivered'].indexOf(job.status);
              return (
                <div key={s} className={current >= i ? 'reached' : ''}>
                  <span>
                    {current > i || done ? (
                      <Check size={13} />
                    ) : current === i ? (
                      <span className="status-dot" />
                    ) : (
                      i + 1
                    )}
                  </span>
                  <strong>{s}</strong>
                  {i < 2 && <i />}
                </div>
              );
            })}
          </div>
          {error && (
            <p className="error-message" role="alert">
              {error}
            </p>
          )}
        </section>
        <aside className="job-sidebar">
          <div className="job-style">
            <StyleArtwork style={job.style} />
            <div>
              <span className="eyebrow muted">THE CREATIVE DIRECTION</span>
              <h3>
                <Link href={`/styles/${job.style.id}`}>{job.style.name}</Link>
              </h3>
              <div className="seller-line">
                <Avatar handle={job.style.seller.handle} />@{job.style.seller.handle}
              </div>
              <div className="card-bottom">
                <Usdc amount={job.priceUsdc} />
                <span className="payment-paid">
                  {job.paymentStatus === 'confirmed' ? (
                    <>
                      <Check size={12} />
                      {sandbox ? 'Sandbox paid' : 'Demo paid'}
                    </>
                  ) : (
                    'Payment pending'
                  )}
                </span>
              </div>
            </div>
          </div>
          <PaymentProof job={job} />
          <div className="job-brief">
            <h3>Your starting point</h3>
            {job.inputImageUrl && (
              <div className="input-thumb">
                <img src={job.inputImageUrl} alt="Original input image" />
                <span>
                  {job.brandName || 'Your original image'}
                  <small>INPUT IMAGE</small>
                </span>
              </div>
            )}
            <label>{job.inputImageUrl ? 'THE BRIEF' : 'TEXT TO IMAGE'}</label>
            <p>{job.buyerBrief}</p>
            {job.requestSource === 'agent' && (
              <p className="mode-note">
                Ordered by your agent ·{' '}
                {sandbox ? 'pay.sh sandbox checkout' : 'simulated USDC checkout'}
              </p>
            )}
            {job.paymentReceipt && !job.paymentReceipt.evidence && (
              <div className="mode-note" style={{ overflowWrap: 'anywhere' }}>
                <strong>Pay.sh sandbox receipt</strong>
                <p>
                  {job.paymentReceipt.amountUsdc.toFixed(2)} test USDC · MPP · balance evidence
                  pending
                </p>
                <p>
                  Transaction: <code>{job.paymentReceipt.transaction}</code>
                </p>
                <p>
                  Seller sandbox wallet: <code>{job.paymentReceipt.recipient}</code>
                </p>
              </div>
            )}
            <Tags tags={job.desiredTags} />
            {job.selectedByAgent && (
              <div className="agent-reason">
                <Sparkles size={17} />
                <div>
                  <strong>Picked by your buyer agent</strong>
                  <p>{job.decisionReason}</p>
                </div>
              </div>
            )}
            <div className="mode-note">
              {job.generationMode === 'mock'
                ? `${job.executionMode === 'worker' ? 'Composed on the seller’s machine and delivered over HTTP.' : 'Made with our local demo compositor.'} A deterministic demo poster using your brief and style palette; no AI model was used.`
                : 'Signature style. One image at a time.'}
            </div>
          </div>
          {done && (
            <Link
              href={`/create?style=${job.styleListingId}`}
              className="button button-light button-full"
            >
              Make another <ArrowRight size={16} />
            </Link>
          )}
        </aside>
      </div>
    </div>
  );
}
